version: "3"

services:
  load_balancer:
    image: nginx:latest
    ports:
      - "3000:8080"
    volumes:
      - ./load-balancer/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend

  frontend:
    build:
      context: frontend
    depends_on:
      - backend

  backend:
    build:
      context: backend
    environment:
      PORT: 3000
      DB_URL: mongodb://mongodb:27017/mydatabase
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - mongo:/data/db

volumes:
  mongo:
